### ISSUE TITLE
v5.2.3, v5.3.0 [logInWithPermissions:fromViewController:handler:] always returns canceled - iOS 13 Xcode 11 beta 5

### ISSUE THREAD

**Issue by GitTheCode** [facebook/facebook-objc-sdk#1013]
**Checklist**
  I've updated to the latest released version of the SDK
  - Yea - I've tried 5.2.2, 5.2.3 and 5.3.0 - none of these are working properly.
  I've searched for existing GitHub issues 
 - there *ARE* other issues but are filed for the swift SDK but calling out the Obj-C SDK - I am basically duplicating that here in the proper SDK.
  I've looked for existing answers on Stack Overflow and the Facebook Developers Group
  I've read the Code of Conduct
  This issue is not security related and can safely be disclosed publicly on GitHub

**Environment**
Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

Xcode Version: 11.0 Beta 5
iOS Version: 13 Beta 5
Swift Version: 5.1
Installation Platform & Version: Directly linking with static libs

**Goals**
Login With Facebook

**Expected Results**
Perform login without canceling in Safari

**Actual Results**
Login always returns with result.isCancelled set to true.
No Safari WebViewController is presented...

**Steps to Reproduce:**
Pretty simple - just create a login manager and try to login.  The exact code is working fine in production for iOS11/12 using earlier library versions.

**Code Samples & Details**
    ```
//      [[FBSDKApplicationDelegate sharedInstance] application:application
                             didFinishLaunchingWithOptions:launchOptions]; is called in didFinishWithOptions... 

[FBSDKSettings setAppID:[TCFacebookAuthManager facebookAppId]];
  
    self.fbLoginManager = [[FBSDKLoginManager alloc] init];
    // do not use native sign in flow - force the use of browser
    self.fbLoginManager.loginBehavior = FBSDKLoginBehaviorBrowser;
    NSArray *permissions = @[@"email", @"user_location"];
    [self.fbLoginManager logInWithPermissions:permissions fromViewController:self.presentingViewController handler:^
     (FBSDKLoginManagerLoginResult *result, NSError *error) {
        if (error != nil) {
            [self handleFacebookLoginFailed:FacebookRegistrationErrorCancel];
            return;
        }
        if (result.isCancelled) {
            // ** this is the return path I am observing with v5.3.0 SDK
            [self handleFacebookLoginFailed:FacebookRegistrationErrorCancel];
            return;
        }
        if (result.grantedPermissions.count == 0) {
            [self handleFacebookLoginFailed:FacebookRegistrationErrorAppBlocked];
            return;
        }
        [self continueFlowGetUserInfo];
     }];
```

**Comment by marianoprettysimple** [comment]
I was having the same exact problem as you (I posted on the Swift repo issue tracker as this was not available for ObjC a few weeks ago), but now I retried on iOS 13 beta 7 and it seems to work fine.

**Comment by GitTheCode** [comment]
Interesting... I just updated to iOS13 Beta 7 and pulled down and build with the latest v5.4.0 SDK and I still see the same issue.

**Comment by hansemannn** [comment]
Same issue - iOS 13 Beta 7 + FB SDK 5.x (including 5.2.2, 5.3.0 and 5.4.0 which all were supposed to fix the issue). I hope this can be prioritized soon as it blocks iOS 13 compatibility right now.

**Comment by kdantley** [comment]
https://github.com/facebook/facebook-objc-sdk/issues/1013#issuecomment-522139183

**Comment by dreamolight** [comment]
@GitTheCode Have you tried to integrate SDK via cocoapods, I'm wondering whether this issue only exists in compiled binary.

**Comment by hansemannn** [comment]
@dreamolight We also use the compiled one. It would be interested if that can cause issues.

**Comment by marianoprettysimple** [comment]
> ~I was having the same exact problem as you (I posted on the Swift repo issue tracker as this was not available for ObjC a few weeks ago), but now I retried on iOS 13 beta 7 and it seems to work fine.~ 

Sorry about the confusion, I must have tested on the wrong branch. I still have this behavior on iOS 13 beta 7, FB SDK 5.4.0 😞 

> We also use the compiled one. It would be interested if that can cause issues.

We're using the compiled frameworks too.

**Comment by marianoprettysimple** [comment]
> @dreamolight We also use the compiled one. It would be interested if that can cause issues.

So I replaced the static frameworks with the source code version and that fixed the issue. 

I'd be interested to hear if someone else can do the same experiment and share their results. It takes just a few minutes. (To save you some time: make sure to compile FBSDKDynamicFrameworkLoader.m with _-fno-objc-arc_ and I had to change any `#import <FBSDKCoreKit/FBSDKAppEvents.h>` to `#import <FBSDKCoreKit/AppEvents/FBSDKAppEvents.h>` in the SDK source.)

**Comment by dreamolight** [comment]
We used some compile time flags to determine whether to add extra process for iOS 13 beta, and the compiled libraries were built via Xcode 10.1, which fails the flag checking. I'll fix the issue for compiled libraries and release a new version by the end of tomorrow.

**Comment by hansemannn** [comment]
It seems to be [merged to master](https://github.com/facebook/facebook-objc-sdk/commit/7022e4d38718d912730ca4fa5f84ccefa962fc28) already, so a patch release should be available soon.

**Comment by dreamolight** [comment]
The fix has been shipped in 5.4.1.

**Comment by hansemannn** [comment]
Still not working with the compiled binary. Come on guys …

**Comment by dreamolight** [comment]
Did you test against 5.4.1 or 5.4.0? I've tested with LoginSample with 5.4.1 compiled binary on Xcode beta, and it works fine.

**Comment by hansemannn** [comment]
I have tested with v5.4.1 and the compiled FBSDKCoreKit, FBSDKLoginKit, FBSDKPlacesKit and FBSDKShareKit libraries. The login is cancelled immediately after calling `loginWithPermissions:fromViewController:handler:`.

**Comment by joesus** [comment]
Looks like this is resolved. Closing.

**Comment by developweb10** [comment]
still facing this issue in objective c sdk facebook login "-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)""

**Comment by joesus** [comment]
@developweb10 please open a new issue with a reproducible sample. This will help us troubleshoot more effectively.
